package org.codirex.publisher.targets.github

import org.codirex.publisher.credentials.CredentialResolver
import org.gradle.api.Project
import org.gradle.api.publish.PublishingExtension

/**
 * Registers a Maven repository pointing at GitHub Packages for the given
 * repo, so the standard `publish...ToGithubPackagesRepository` task
 * (auto-generated by maven-publish) pushes there directly.
 *
 * Configuration-time only (constructed once, from
 * [org.codirex.publisher.engine.MavenPublishOrchestrator]) - never stored on
 * a Task, so holding `Project` here is fine.
 */
class GithubPackagesClient(
    private val project: Project,
    private val repoFullName: String,
    private val credentials: CredentialResolver
) {

    fun register() {
        val publishing = project.extensions.getByType(PublishingExtension::class.java)

        publishing.repositories.maven { repo ->
            repo.name = "GithubPackages"
            repo.url = project.uri("https://maven.pkg.github.com/$repoFullName")
            repo.credentials { creds ->
                creds.username = credentials.requireGithubUsername(project.path)
                creds.password = credentials.requireGithubToken(project.path)
            }
        }
    }
}
