package org.codirex.publisher.targets.github

import org.codirex.publisher.credentials.CredentialResolver
import org.gradle.api.Project
import org.gradle.api.publish.PublishingExtension

/**
 * Registers a Maven repository pointing at GitHub Packages for the given
 * repo, so the standard `publish...ToGithubPackagesRepository` task
 * (auto-generated by maven-publish) pushes there directly.
 */
class GithubPackagesClient(private val project: Project, private val repoFullName: String) {

    fun register() {
        val credentials = CredentialResolver(project).requireGithub()
        val publishing = project.extensions.getByType(PublishingExtension::class.java)

        publishing.repositories.maven { repo ->
            repo.name = "GithubPackages"
            repo.url = project.uri("https://maven.pkg.github.com/$repoFullName")
            repo.credentials { creds ->
                creds.username = credentials.username
                creds.password = credentials.token
            }
        }
    }
}
